# PB — S-3 Output Boundary: no resident PII / credential marker in the report
#
# MFG-C2-058's S-3 guarantee for the rendered robotics incident report has two
# layers, both asserted here:
#
#  (1) End-to-end operator-PII stripping (TestS3NoPiiLeakInReport):
#      the report is synthesized ONLY from the already-sanitized telemetry.
#      Operator PII (e-mail / phone / badge id) injected at the input is
#      surface-stripped by the outer PreProcessNode (→ validated_input) BEFORE
#      the inner domain workflow ever parses it, so it can never surface in
#      compliance_validated_report.
#
#  (2) S-3 credential output gate (TestS3CredentialGate):
#      PostProcessNode implements `_security_gate_output()` (the framework rules §5-6)
#      and blocks credential-like content (API keys, JWT, Bearer tokens, raw
#      credential assignments) in the surfaced report — replacing BOTH
#      formatted_output and result with a sanitised stub and ERROR status. This
#      is the mandatory S-3 credential-block boundary test, driven directly
#      against the outer post_process slot.
#
# Deterministic — no LLM, no network. framework.* / src.* imports only.

import json


from framework.schemas.agent_status import AgentStatus
from framework.schemas.invocation_context import InvocationContext

from src.graph.graph import Graph
from src.nodes.post_process_node import PostProcessNode


# Simulated operator-PII tokens — NOT real data.
_EMAIL = "operator.taro@example.com"
_PHONE = "03-9876-5432"
_BADGE = "EMP-554433"

# A compliant mechanical-failure payload (known type → run succeeds) with
# operator PII embedded in free-text + a PII-named field.
_PAYLOAD_WITH_PII = json.dumps(
    {
        "robot_id": "R-LINE3-07",
        "error_codes": ["MEC-014"],
        "sensor_readings": {"torque": 91.0, "temp_c": 78.0},
        "operator_contact": f"{_EMAIL} / {_PHONE}",
        "free_text": (
            f"Servo motor overheating with abnormal torque. Reported by {_BADGE}, " f"contact {_EMAIL}, tel {_PHONE}."
        ),
    },
    ensure_ascii=False,
)


def _run(user_input: str) -> dict:
    # Fully-trusted internal context — the backbone S-1 gate denies ANONYMOUS.
    ctx = InvocationContext.for_internal(caller_id="test-suite")
    return Graph().invoke(user_input, ctx=ctx)


class TestS3NoPiiLeakInReport:
    """PB (S-3): the rendered report carries no injected operator-PII token."""

    def test_run_succeeds(self):
        result = _run(_PAYLOAD_WITH_PII)
        assert (
            result.get("status") == AgentStatus.SUCCESS.value
        ), f"Expected success, got {result.get('status')}. result={result!r}"

    def test_email_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _EMAIL not in report, "Operator e-mail leaked into the report"

    def test_phone_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _PHONE not in report, "Operator phone number leaked into the report"

    def test_badge_not_in_report(self):
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert _BADGE not in report, "Operator badge id leaked into the report"

    def test_report_still_non_empty(self):
        """Stripping PII must not blank the report — the structure survives."""
        report = _run(_PAYLOAD_WITH_PII).get("output", "")
        assert report.strip()
        assert "Robotics Incident Report" in report


# Simulated credential patterns — NOT real credentials.
_SIMULATED_API_KEY = "sk-TESTKEY1234567890abcdefghijklmn"
_SIMULATED_JWT = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
_SIMULATED_BEARER = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
_SIMULATED_CRED_STR = "password=super_secret_password_abc123"

# A clean robotics-style report (no credential strings) — must pass the gate.
_CLEAN_REPORT = """\
# Robotics Incident Report

**Robot ID:** R-LINE3-07
**MHLW/METI Compliance:** PASS

---

## Summary

Robot R-LINE3-07 reported a mechanical_failure; severity HIGH.

## Corrective Actions

- Isolate the affected axis and inspect for wear.

---

*Generated by MFG-C2-058. No raw telemetry or operator personal data is \
reproduced in this report.*
"""


class TestS3CredentialGate:
    """PB (S-3, MANDATORY): PostProcessNode blocks credential-like output content.

    Drives PostProcessNode directly (the outer post_process slot is the S-3
    gate point). An injected secret in state["result"] must yield ERROR status
    and a sanitised stub for BOTH formatted_output and result — the raw secret
    must never survive into the surfaced output.
    """

    def test_api_key_in_result_is_blocked(self):
        report_with_key = "# Robotics Incident Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        assert (
            result.get("status") == AgentStatus.ERROR.value
        ), f"Expected ERROR (S-3 block), got {result.get('status')}."

    def test_api_key_not_in_output_after_block(self):
        report_with_key = "# Robotics Incident Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        # Gate BOTH surfaced fields.
        assert _SIMULATED_API_KEY not in result.get(
            "formatted_output", ""
        ), "Simulated API key leaked into formatted_output"
        assert _SIMULATED_API_KEY not in result.get("result", ""), "Simulated API key leaked into result"

    def test_blocked_output_is_sanitised_stub(self):
        report_with_key = "# Robotics Incident Report\n\n## Notes\n" f"<!-- debug: api_key={_SIMULATED_API_KEY} -->\n"
        result = PostProcessNode().execute({"result": report_with_key})
        for field in ("formatted_output", "result"):
            output = result.get(field, "")
            assert (
                "WITHHELD" in output or "withheld" in output.lower()
            ), f"Expected the withheld notice in blocked {field}, got: {output[:200]!r}"
            # Truthy, not empty: a falsy replacement re-opens get_output()'s
            # `formatted_output or result` fallback to the ungated report.
            assert output
        assert result.get("error_log"), "Blocked output must carry an error_log entry"

    def test_credential_assignment_in_result_is_blocked(self):
        report_with_cred = "# Robotics Incident Report\n\n## Config\n" f"Internal note: {_SIMULATED_CRED_STR}\n"
        result = PostProcessNode().execute({"result": report_with_cred})
        assert result.get("status") == AgentStatus.ERROR.value
        assert _SIMULATED_CRED_STR not in result.get("formatted_output", "")
        assert _SIMULATED_CRED_STR not in result.get("result", "")

    def test_jwt_in_result_is_blocked(self):
        report_with_jwt = "# Robotics Incident Report\n\n## Notes\n" f"Token observed: {_SIMULATED_JWT}\n"
        result = PostProcessNode().execute({"result": report_with_jwt})
        assert result.get("status") == AgentStatus.ERROR.value

    def test_bearer_token_in_result_is_blocked(self):
        report_with_bearer = "# Robotics Incident Report\n\n## Notes\n" f"Authorization: {_SIMULATED_BEARER}\n"
        result = PostProcessNode().execute({"result": report_with_bearer})
        assert result.get("status") == AgentStatus.ERROR.value

    def test_clean_report_passes_s3_gate(self):
        """A clean robotics-style report must NOT trip the gate (SUCCESS, unchanged)."""
        result = PostProcessNode().execute({"result": _CLEAN_REPORT})
        assert result.get("status") == AgentStatus.SUCCESS.value, (
            f"Clean report should pass S-3 gate, got {result.get('status')}. " f"error_log: {result.get('error_log')}"
        )
        assert (
            result.get("formatted_output") == _CLEAN_REPORT
        ), "Clean report must pass through formatted_output unchanged"
